version: '3.8'
services:
  asterisk:
    image: andrius/asterisk:latest
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10010:10000-10010/udp"
    volumes:
      - ./asterisk-config:/etc/asterisk
    networks:
      - asterisk-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: homer_db
      POSTGRES_USER: homer_user
      POSTGRES_PASSWORD: homer_password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - asterisk-net

networks:
  asterisk-net: 

volumes:
  postgres-data:
